version: '3'
services:
  mysql:
    image: "mysql:5.7"
    restart: "always"
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"